services:
  - type: web
    name: sequoia-institutional-aum
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_insto:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
